import { FC, PropsWithChildren, useState } from 'react'
import Head from 'next/head'
import { Container } from '@nextui-org/react'

import { Loader, SocialMedia } from '../home'
import { Footer, NavbarApp } from '../ui'


// TODO: Add the necessary metadata in the page header
export const MainLayout: FC<PropsWithChildren> = ({ children }) => {

    const [isLoading, setIsLoading] = useState(true)

    const handleFinish = () => setIsLoading(false)

    return (
        <>
            <Head>
                <title>Rafael Sequeira | Full-Stack Developer</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                isLoading ? (
                    <Loader onFinish={handleFinish} />
                ) : (
                    <>
                        <NavbarApp />

                        <Container sm css={{ position: "relative", zIndex: 1 }}>
                            {children}
                        </Container>

                        <SocialMedia />

                        <Footer />
                    </>
                )
            }

        </>
    )
}